# Generated by Django 3.2.5 on 2021-07-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='proce',
            new_name='price',
        ),
    ]
